# Generated by Django 4.0.1 on 2024-07-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.TextField(blank=True, max_length=335, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.TextField(blank=True, max_length=335, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.TextField(blank=True, max_length=335, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
