# Generated by Django 5.0.1 on 2024-06-10 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='contests',
        ),
        migrations.DeleteModel(
            name='ContestEntry',
        ),
    ]
