# Generated by Django 4.0.1 on 2024-09-24 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_city_profile_country_profile_state_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Referral',
        ),
    ]
