# Generated by Django 4.0.1 on 2024-06-23 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_referral_people_profile_referred_by_referral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='bank_name',
        ),
        migrations.AlterField(
            model_name='profile',
            name='referral_people',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngn_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
