# Generated by Django 4.0.1 on 2024-06-23 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_deposit_account_number_remove_deposit_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='ngn_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
