# Generated by Django 4.0.1 on 2024-06-23 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_payment_ngn_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='ngn_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
