# Generated by Django 4.0.1 on 2024-06-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_payment_ngn_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdraw',
            name='amount',
        ),
        migrations.AddField(
            model_name='withdraw',
            name='reference',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
