# Generated by Django 4.0.1 on 2024-10-10 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_emailverificationtotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerificationTOTP',
        ),
    ]
