# Generated by Django 4.0.1 on 2024-07-15 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('image_url', models.CharField(max_length=250)),
                ('team_id', models.IntegerField(default=0)),
                ('fixture_id', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('position', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContestHistory',
            fields=[
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('entry_amount', models.IntegerField(default=0)),
                ('entered_by', models.DateTimeField(auto_now_add=True)),
                ('action_title', models.CharField(blank=True, max_length=100, null=True)),
                ('pending', models.BooleanField(default=True)),
                ('completed', models.BooleanField(default=False)),
                ('total_points', models.IntegerField(default=0)),
                ('position', models.IntegerField(default=0)),
                ('won_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pool_price', models.IntegerField(default=0)),
                ('players', models.ManyToManyField(blank=True, to='contests.Player')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
