# Generated by Django 5.0.1 on 2024-04-07 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='contests_co_name_48a5c6_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContestLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'level',
                'ordering': ['level'],
                'indexes': [models.Index(fields=['level'], name='contests_co_level_cb2230_idx')],
            },
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('start_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('end_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('max_entries', models.IntegerField(blank=True, default=0, null=True)),
                ('entries', models.IntegerField(blank=True, default=0, null=True)),
                ('entry_fee', models.IntegerField(blank=True, default=0, null=True)),
                ('prize_pool', models.IntegerField(blank=True, default=0, null=True)),
                ('management_fee', models.IntegerField(blank=True, default=0, null=True)),
                ('total_salary', models.IntegerField(default=0)),
                ('allow_multiple_entries', models.BooleanField(default=False)),
                ('max_multi_entries', models.IntegerField(blank=True, default=0, null=True)),
                ('is_live', models.BooleanField(default=False)),
                ('is_upcoming', models.BooleanField(default=False)),
                ('is_ended', models.BooleanField(default=False)),
                ('is_recommended', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestCat', to='contests.contestcategory')),
                ('level', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='contests.contestlevel')),
            ],
        ),
    ]
