# Generated by Django 4.0.1 on 2024-07-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contesthistory',
            name='action_title',
        ),
        migrations.AddField(
            model_name='contesthistory',
            name='league_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
