# Generated by Django 5.0.1 on 2024-06-10 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
        ('profiles', '0002_remove_profile_contests_delete_contestentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='category',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='level',
        ),
        migrations.DeleteModel(
            name='ContestCategory',
        ),
        migrations.DeleteModel(
            name='Contest',
        ),
        migrations.DeleteModel(
            name='ContestLevel',
        ),
    ]
