# Generated by Django 4.0.1 on 2024-07-20 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_remove_contesthistory_action_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contesthistory',
            name='profile',
        ),
    ]
