# Generated by Django 4.0.1 on 2024-07-20 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('contests', '0003_remove_contesthistory_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='contesthistory',
            name='profile',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
            preserve_default=False,
        ),
    ]
