# Generated by Django 4.0.1 on 2024-07-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_contesthistory_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='contesthistory',
            name='fixture_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
