# Generated by Django 4.0.1 on 2024-07-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0006_alter_contesthistory_fixture_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contesthistory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
