# Generated by Django 4.0.1 on 2024-07-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0008_player_player_id_alter_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contesthistory',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
