# Generated by Django 4.0.1 on 2024-07-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0009_alter_contesthistory_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contesthistory',
            name='profit',
            field=models.BooleanField(default=False),
        ),
    ]
