# Generated by Django 4.0.1 on 2024-07-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0010_contesthistory_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contesthistory',
            name='total_points',
            field=models.FloatField(default=0.0),
        ),
    ]
