# Generated by Django 4.0.1 on 2024-07-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0011_alter_contesthistory_total_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='contesthistory',
            name='game_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contesthistory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
