# Generated by Django 4.0.1 on 2024-07-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0012_contesthistory_game_id_alter_contesthistory_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contesthistory',
            name='positions',
            field=models.BooleanField(default=False),
        ),
    ]
