# Generated by Django 4.0.1 on 2024-07-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0013_contesthistory_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='contesthistory',
            name='max_pool',
            field=models.IntegerField(default=0),
        ),
    ]
