# Generated by Django 4.0.1 on 2024-07-24 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0014_contesthistory_max_pool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contesthistory',
            old_name='max_pool',
            new_name='max_entry',
        ),
    ]
