# Generated by Django 4.0.1 on 2024-09-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0015_rename_max_pool_contesthistory_max_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional title for the slider item', max_length=255, null=True)),
                ('text', models.TextField(help_text='Text content for the slider', max_length=500)),
                ('image', models.ImageField(blank=True, help_text='Upload SVG/PNG images', null=True, upload_to='slider_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
