# Generated by Django 4.0.1 on 2024-09-28 13:22

import contests.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0016_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.FileField(blank=True, help_text='Upload SVG/PNG images', null=True, upload_to='slider_images/', validators=[contests.validators.FileValidator()]),
        ),
        migrations.AlterField(
            model_name='slider',
            name='text',
            field=models.TextField(help_text='Text content for the slider', max_length=300),
        ),
    ]
